name: ZoneManager
main: com.endmceval.ZoneManagers
version: 1.0.0
author: YourName
api-version: 1.16
commands:
  zone:
    description: Zone management command
    usage: /zone <args>
permissions:
  zonemanager.admin:
    description: Admin permission for zone management
    default: op 